name: CI
on:
  push: {}
  pull_request: {}
jobs:
  checks:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false

      - name: Build
        run: |
          make build

      - name: Test
        run: |
          make test

      - name: Publish code coverage results
        run: |
          go test -race -coverprofile=coverage.txt -covermode=atomic ./...
          bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
