name: CI
on: push
jobs:
  checks:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Build
        uses: cedrickring/golang-action@1.6.0
        with:
          args: make build

      - name: Test
        uses: cedrickring/golang-action@1.6.0
        with:
          args: make test

      - name: Publish code coverage results
        run: |
          go test -race -coverprofile=coverage.txt -covermode=atomic ./...
          bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
